version: "3.9"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "mmodb"
      POSTGRES_USER: "yarteshc"
      POSTGRES_PASSWORD: "yarteshc"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - mmodb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mmodb-data: